<?xml version="1.0" encoding="UTF-8"?>
<testng-results total="35" passed="26" failed="9" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2020-05-10T05:17:59Z" name="RestAssureTestSuite" finished-at="2020-05-10T05:18:34Z" duration-ms="35414">
    <groups>
    </groups>
    <test started-at="2020-05-10T05:17:59Z" name="RestAssureTestSuite" finished-at="2020-05-10T05:18:34Z" duration-ms="35414">
      <class name="com.RestAssured.SDET.TestCase.T002_POST_Request">
        <test-method signature="postWeatherDetails()[pri:0, instance:com.RestAssured.SDET.TestCase.T002_POST_Request@609cd4d8]" started-at="2020-05-10T01:18:00Z" name="postWeatherDetails" finished-at="2020-05-10T01:18:00Z" duration-ms="234" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [201] but found [200]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [201] but found [200]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at org.testng.Assert.assertEquals(Assert.java:399)
	at com.RestAssured.SDET.TestCase.T002_POST_Request.postWeatherDetails(T002_POST_Request.java:42)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postWeatherDetails -->
      </class> <!-- com.RestAssured.SDET.TestCase.T002_POST_Request -->
      <class name="com.RestAssured.SDET.TestCase.T005_GET_JSON_RESPONSE">
        <test-method signature="getWeatherDetails()[pri:0, instance:com.RestAssured.SDET.TestCase.T005_GET_JSON_RESPONSE@13b6aecc]" started-at="2020-05-10T01:18:01Z" name="getWeatherDetails" finished-at="2020-05-10T01:18:01Z" duration-ms="305" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getWeatherDetails -->
      </class> <!-- com.RestAssured.SDET.TestCase.T005_GET_JSON_RESPONSE -->
      <class name="com.RestAssured.SDET.TestCase.TC003_Post_Employee_Record">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.RestAssured.SDET.TestCase.TC003_Post_Employee_Record@1e66f1f5]" started-at="2020-05-10T01:18:18Z" name="setup" finished-at="2020-05-10T01:18:18Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method is-config="true" signature="createEmployee()[pri:0, instance:com.RestAssured.SDET.TestCase.TC003_Post_Employee_Record@1e66f1f5]" started-at="2020-05-10T01:18:18Z" name="createEmployee" finished-at="2020-05-10T01:18:24Z" duration-ms="6438" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createEmployee -->
        <test-method signature="checkContaintType()[pri:0, instance:com.RestAssured.SDET.TestCase.TC003_Post_Employee_Record@1e66f1f5]" started-at="2020-05-10T01:18:24Z" name="checkContaintType" finished-at="2020-05-10T01:18:24Z" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkContaintType -->
        <test-method signature="checkResponseBody()[pri:0, instance:com.RestAssured.SDET.TestCase.TC003_Post_Employee_Record@1e66f1f5]" started-at="2020-05-10T01:18:24Z" name="checkResponseBody" finished-at="2020-05-10T01:18:24Z" duration-ms="1" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [{"status":"success","data":{"name":"JohnJ","salary":"82831","age":"97","id":63}}82831]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [{"status":"success","data":{"name":"JohnJ","salary":"82831","age":"97","id":63}}82831]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:179)
	at com.RestAssured.SDET.TestCase.TC003_Post_Employee_Record.checkResponseBody(TC003_Post_Employee_Record.java:55)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkResponseBody -->
        <test-method signature="checkServerType()[pri:0, instance:com.RestAssured.SDET.TestCase.TC003_Post_Employee_Record@1e66f1f5]" started-at="2020-05-10T01:18:24Z" name="checkServerType" finished-at="2020-05-10T01:18:24Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkServerType -->
        <test-method signature="checkStatusCode()[pri:0, instance:com.RestAssured.SDET.TestCase.TC003_Post_Employee_Record@1e66f1f5]" started-at="2020-05-10T01:18:24Z" name="checkStatusCode" finished-at="2020-05-10T01:18:24Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkStatusCode -->
        <test-method signature="checkStatusLine()[pri:0, instance:com.RestAssured.SDET.TestCase.TC003_Post_Employee_Record@1e66f1f5]" started-at="2020-05-10T01:18:24Z" name="checkStatusLine" finished-at="2020-05-10T01:18:24Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkStatusLine -->
        <test-method signature="tearDown()[pri:0, instance:com.RestAssured.SDET.TestCase.TC003_Post_Employee_Record@1e66f1f5]" started-at="2020-05-10T01:18:24Z" name="tearDown" finished-at="2020-05-10T01:18:24Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.RestAssured.SDET.TestCase.TC003_Post_Employee_Record -->
      <class name="com.RestAssured.SDET.TestCase.T003_GET_Request">
        <test-method signature="getGoogleMapTest()[pri:0, instance:com.RestAssured.SDET.TestCase.T003_GET_Request@17f7cd29]" started-at="2020-05-10T01:18:00Z" name="getGoogleMapTest" finished-at="2020-05-10T01:18:01Z" duration-ms="695" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getGoogleMapTest -->
      </class> <!-- com.RestAssured.SDET.TestCase.T003_GET_Request -->
      <class name="com.RestAssured.SDET.TestCase.T007_GET_Autherization">
        <test-method signature="AuthorizationTest()[pri:0, instance:com.RestAssured.SDET.TestCase.T007_GET_Autherization@3c3d9b6b]" started-at="2020-05-10T01:18:02Z" name="AuthorizationTest" finished-at="2020-05-10T01:18:02Z" duration-ms="216" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AuthorizationTest -->
      </class> <!-- com.RestAssured.SDET.TestCase.T007_GET_Autherization -->
      <class name="com.RestAssured.SDET.TestCase.T004_GET_All_Headers">
        <test-method signature="getWeatherDetails()[pri:0, instance:com.RestAssured.SDET.TestCase.T004_GET_All_Headers@7d8704ef]" started-at="2020-05-10T01:18:01Z" name="getWeatherDetails" finished-at="2020-05-10T01:18:01Z" duration-ms="179" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getWeatherDetails -->
      </class> <!-- com.RestAssured.SDET.TestCase.T004_GET_All_Headers -->
      <class name="com.RestAssured.SDET.TestCase.TC001_Get_All_Employees">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.RestAssured.SDET.TestCase.TC001_Get_All_Employees@79d8407f]" started-at="2020-05-10T01:18:02Z" name="setup" finished-at="2020-05-10T01:18:02Z" duration-ms="18" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method is-config="true" signature="getAllEmployees()[pri:0, instance:com.RestAssured.SDET.TestCase.TC001_Get_All_Employees@79d8407f]" started-at="2020-05-10T01:18:02Z" name="getAllEmployees" finished-at="2020-05-10T01:18:11Z" duration-ms="9178" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getAllEmployees -->
        <test-method signature="checkContaintType()[pri:0, instance:com.RestAssured.SDET.TestCase.TC001_Get_All_Employees@79d8407f]" started-at="2020-05-10T01:18:11Z" name="checkContaintType" finished-at="2020-05-10T01:18:11Z" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkContaintType -->
        <test-method signature="checkContentLength()[pri:0, instance:com.RestAssured.SDET.TestCase.TC001_Get_All_Employees@79d8407f]" started-at="2020-05-10T01:18:11Z" name="checkContentLength" finished-at="2020-05-10T01:18:11Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkContentLength -->
        <test-method signature="checkResponseBody()[pri:0, instance:com.RestAssured.SDET.TestCase.TC001_Get_All_Employees@79d8407f]" started-at="2020-05-10T01:18:11Z" name="checkResponseBody" finished-at="2020-05-10T01:18:11Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkResponseBody -->
        <test-method signature="checkResponseTime()[pri:0, instance:com.RestAssured.SDET.TestCase.TC001_Get_All_Employees@79d8407f]" started-at="2020-05-10T01:18:11Z" name="checkResponseTime" finished-at="2020-05-10T01:18:11Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkResponseTime -->
        <test-method signature="checkServerType()[pri:0, instance:com.RestAssured.SDET.TestCase.TC001_Get_All_Employees@79d8407f]" started-at="2020-05-10T01:18:11Z" name="checkServerType" finished-at="2020-05-10T01:18:11Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkServerType -->
        <test-method signature="checkStatusCode()[pri:0, instance:com.RestAssured.SDET.TestCase.TC001_Get_All_Employees@79d8407f]" started-at="2020-05-10T01:18:11Z" name="checkStatusCode" finished-at="2020-05-10T01:18:11Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkStatusCode -->
        <test-method signature="checkStatusLine()[pri:0, instance:com.RestAssured.SDET.TestCase.TC001_Get_All_Employees@79d8407f]" started-at="2020-05-10T01:18:11Z" name="checkStatusLine" finished-at="2020-05-10T01:18:11Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkStatusLine -->
        <test-method signature="checkingEncoding()[pri:0, instance:com.RestAssured.SDET.TestCase.TC001_Get_All_Employees@79d8407f]" started-at="2020-05-10T01:18:11Z" name="checkingEncoding" finished-at="2020-05-10T01:18:11Z" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkingEncoding -->
        <test-method signature="getCookies()[pri:0, instance:com.RestAssured.SDET.TestCase.TC001_Get_All_Employees@79d8407f]" started-at="2020-05-10T01:18:11Z" name="getCookies" finished-at="2020-05-10T01:18:11Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getCookies -->
        <test-method signature="tearDown()[pri:0, instance:com.RestAssured.SDET.TestCase.TC001_Get_All_Employees@79d8407f]" started-at="2020-05-10T01:18:11Z" name="tearDown" finished-at="2020-05-10T01:18:11Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.RestAssured.SDET.TestCase.TC001_Get_All_Employees -->
      <class name="com.RestAssured.SDET.TestCase.T006_GET_ExtractValueofEachNode_JSON">
        <test-method signature="getWeatherDetailsJOSN()[pri:0, instance:com.RestAssured.SDET.TestCase.T006_GET_ExtractValueofEachNode_JSON@158a8276]" started-at="2020-05-10T01:18:01Z" name="getWeatherDetailsJOSN" finished-at="2020-05-10T01:18:02Z" duration-ms="555" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [340 Degree] but found [110 Degree]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [340 Degree] but found [110 Degree]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:179)
	at com.RestAssured.SDET.TestCase.T006_GET_ExtractValueofEachNode_JSON.getWeatherDetailsJOSN(T006_GET_ExtractValueofEachNode_JSON.java:33)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getWeatherDetailsJOSN -->
      </class> <!-- com.RestAssured.SDET.TestCase.T006_GET_ExtractValueofEachNode_JSON -->
      <class name="com.RestAssured.SDET.TestCase.TC002_Get_Single_Employee_Record">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.RestAssured.SDET.TestCase.TC002_Get_Single_Employee_Record@5fbe4146]" started-at="2020-05-10T01:18:11Z" name="setup" finished-at="2020-05-10T01:18:11Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method is-config="true" signature="getAllEmployees()[pri:0, instance:com.RestAssured.SDET.TestCase.TC002_Get_Single_Employee_Record@5fbe4146]" started-at="2020-05-10T01:18:11Z" name="getAllEmployees" finished-at="2020-05-10T01:18:18Z" duration-ms="6559" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getAllEmployees -->
        <test-method signature="checkContentType()[pri:0, instance:com.RestAssured.SDET.TestCase.TC002_Get_Single_Employee_Record@5fbe4146]" started-at="2020-05-10T01:18:18Z" name="checkContentType" finished-at="2020-05-10T01:18:18Z" duration-ms="2" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [text/html;charset=UTF-8] but found [application/json;charset=utf-8]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [text/html;charset=UTF-8] but found [application/json;charset=utf-8]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.RestAssured.SDET.TestCase.TC002_Get_Single_Employee_Record.checkContentType(TC002_Get_Single_Employee_Record.java:81)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkContentType -->
        <test-method signature="checkResponseBody()[pri:0, instance:com.RestAssured.SDET.TestCase.TC002_Get_Single_Employee_Record@5fbe4146]" started-at="2020-05-10T01:18:18Z" name="checkResponseBody" finished-at="2020-05-10T01:18:18Z" duration-ms="1" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.RestAssured.SDET.TestCase.TC002_Get_Single_Employee_Record.checkResponseBody(TC002_Get_Single_Employee_Record.java:30)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkResponseBody -->
        <test-method signature="checkResponseTime()[pri:0, instance:com.RestAssured.SDET.TestCase.TC002_Get_Single_Employee_Record@5fbe4146]" started-at="2020-05-10T01:18:18Z" name="checkResponseTime" finished-at="2020-05-10T01:18:18Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkResponseTime -->
        <test-method signature="checkServerType()[pri:0, instance:com.RestAssured.SDET.TestCase.TC002_Get_Single_Employee_Record@5fbe4146]" started-at="2020-05-10T01:18:18Z" name="checkServerType" finished-at="2020-05-10T01:18:18Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkServerType -->
        <test-method signature="checkStatusCode()[pri:0, instance:com.RestAssured.SDET.TestCase.TC002_Get_Single_Employee_Record@5fbe4146]" started-at="2020-05-10T01:18:18Z" name="checkStatusCode" finished-at="2020-05-10T01:18:18Z" duration-ms="1" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [400]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [400]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at org.testng.Assert.assertEquals(Assert.java:399)
	at com.RestAssured.SDET.TestCase.TC002_Get_Single_Employee_Record.checkStatusCode(TC002_Get_Single_Employee_Record.java:40)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkStatusCode -->
        <test-method signature="checkStatusLine()[pri:0, instance:com.RestAssured.SDET.TestCase.TC002_Get_Single_Employee_Record@5fbe4146]" started-at="2020-05-10T01:18:18Z" name="checkStatusLine" finished-at="2020-05-10T01:18:18Z" duration-ms="1" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [HTTP/1.1 200 OK] but found [HTTP/1.1 400 Bad Request]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [HTTP/1.1 200 OK] but found [HTTP/1.1 400 Bad Request]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.RestAssured.SDET.TestCase.TC002_Get_Single_Employee_Record.checkStatusLine(TC002_Get_Single_Employee_Record.java:50)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkStatusLine -->
        <test-method signature="checkingEncoding()[pri:0, instance:com.RestAssured.SDET.TestCase.TC002_Get_Single_Employee_Record@5fbe4146]" started-at="2020-05-10T01:18:18Z" name="checkingEncoding" finished-at="2020-05-10T01:18:18Z" duration-ms="1" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [gzip] but found [null]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [gzip] but found [null]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:130)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.RestAssured.SDET.TestCase.TC002_Get_Single_Employee_Record.checkingEncoding(TC002_Get_Single_Employee_Record.java:90)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkingEncoding -->
        <test-method signature="getCookies()[pri:0, instance:com.RestAssured.SDET.TestCase.TC002_Get_Single_Employee_Record@5fbe4146]" started-at="2020-05-10T01:18:18Z" name="getCookies" finished-at="2020-05-10T01:18:18Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getCookies -->
        <test-method signature="tearDown()[pri:0, instance:com.RestAssured.SDET.TestCase.TC002_Get_Single_Employee_Record@5fbe4146]" started-at="2020-05-10T01:18:18Z" name="tearDown" finished-at="2020-05-10T01:18:18Z" duration-ms="9" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.RestAssured.SDET.TestCase.TC002_Get_Single_Employee_Record -->
      <class name="com.RestAssured.SDET.TestCase.TC004_Put_Employee_Record">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.RestAssured.SDET.TestCase.TC004_Put_Employee_Record@4e50c791]" started-at="2020-05-10T01:18:24Z" name="setup" finished-at="2020-05-10T01:18:24Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method is-config="true" signature="createEmployee()[pri:0, instance:com.RestAssured.SDET.TestCase.TC004_Put_Employee_Record@4e50c791]" started-at="2020-05-10T01:18:24Z" name="createEmployee" finished-at="2020-05-10T01:18:34Z" duration-ms="9604" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createEmployee -->
        <test-method signature="checkResponseBody()[pri:0, instance:com.RestAssured.SDET.TestCase.TC004_Put_Employee_Record@4e50c791]" started-at="2020-05-10T01:18:34Z" name="checkResponseBody" finished-at="2020-05-10T01:18:34Z" duration-ms="2" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.RestAssured.SDET.TestCase.TC004_Put_Employee_Record.checkResponseBody(TC004_Put_Employee_Record.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkResponseBody -->
        <test-method signature="checkStatusCode()[pri:0, instance:com.RestAssured.SDET.TestCase.TC004_Put_Employee_Record@4e50c791]" started-at="2020-05-10T01:18:34Z" name="checkStatusCode" finished-at="2020-05-10T01:18:34Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkStatusCode -->
        <test-method signature="checkStatusLine()[pri:0, instance:com.RestAssured.SDET.TestCase.TC004_Put_Employee_Record@4e50c791]" started-at="2020-05-10T01:18:34Z" name="checkStatusLine" finished-at="2020-05-10T01:18:34Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkStatusLine -->
      </class> <!-- com.RestAssured.SDET.TestCase.TC004_Put_Employee_Record -->
      <class name="com.RestAssured.SDET.TestCase.T001_GET_Request">
        <test-method signature="getWeatherDetails()[pri:0, instance:com.RestAssured.SDET.TestCase.T001_GET_Request@bccb269]" started-at="2020-05-10T01:17:59Z" name="getWeatherDetails" finished-at="2020-05-10T01:18:00Z" duration-ms="1117" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getWeatherDetails -->
      </class> <!-- com.RestAssured.SDET.TestCase.T001_GET_Request -->
    </test> <!-- RestAssureTestSuite -->
  </suite> <!-- RestAssureTestSuite -->
</testng-results>
